[package]
name = "mathbench"
version = "0.3.0"
authors = ["Cameron Hart <cameron.hart@gmail.com>"]
edition = "2018"

[features]
# defaults can be disabled for benchmarks but are required for tests
default = ["cgmath", "euclid", "nalgebra", "nalgebra_f32x4", "nalgebra_f32x8", "nalgebra_f32x16", "ultraviolet", "vek", "pathfinder_geometry"]
nalgebra_f32x4 = [ "nalgebra", "packed_simd"]
nalgebra_f32x8 = [ "nalgebra", "packed_simd"]
nalgebra_f32x16 = [ "nalgebra", "packed_simd"]



[dependencies]
mint = "0.5.4"
rand = "0.7.2"
rand_pcg = "0.2.1"

[dependencies.glam]
version = "0.8.3"
features = ["mint", "rand", "debug-glam-assert"]
# a lot of random data generation uses glam, so can't be optional yet
# optional = true

[dependencies.nalgebra]
version = "0.20.0"
features = ["std", "mint"]
optional = true

[dependencies.ultraviolet]
version = "0.4"
optional = true

[dependencies.packed_simd]
version = "0.3"
optional = true

[dependencies.cgmath]
version = "0.17.0"
features = ["mint"]
optional = true

[dependencies.euclid]
version = "0.20.5"
features = ["mint"]
optional = true

[dependencies.vek]
version = "0.9.10"
features = ["mint"]
optional = true

[dependencies.pathfinder_geometry]
version = "0.3.0"
optional = true

[dev-dependencies]
criterion = "0.3.0"

# [patch.crates-io]
# glam = { path = "../glam-rs" }

[[bench]]
name = "eulerbench"
harness = false

[[bench]]
name = "quaternion"
harness = false

[[bench]]
name = "matrix2"
harness = false

[[bench]]
name = "matrix3"
harness = false

[[bench]]
name = "matrix4"
harness = false

[[bench]]
name = "transform2d"
harness = false

[[bench]]
name = "transform3d"
harness = false

[[bench]]
name = "transformations"
harness = false

[[bench]]
name = "vector3"
harness = false

[profile.bench]
#debug = true
#lto = true
codegen-units = 1